# Generated by Django 2.2.7 on 2020-04-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0003_auto_20200328_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='pic',
            field=models.ImageField(default='', upload_to='talk_icon'),
        ),
    ]
