# Generated by Django 2.2.7 on 2020-04-13 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0005_auto_20200412_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
