# Generated by Django 2.2.7 on 2020-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0008_auto_20200422_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
