# Generated by Django 2.2.7 on 2020-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0010_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='good',
            field=models.BooleanField(default=True),
        ),
    ]
