# Generated by Django 2.2.7 on 2020-05-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0011_auto_20200425_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='sc_title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share_calendar.Schedule'),
        ),
    ]
