# Generated by Django 2.2.7 on 2020-05-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0014_auto_20200513_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_image',
            name='today',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share_calendar.Today'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
