# Generated by Django 2.2.7 on 2020-06-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0019_auto_20200604_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
