# Generated by Django 2.2.7 on 2020-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0020_auto_20200607_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
