# Generated by Django 3.2 on 2021-04-17 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share_calendar', '0022_auto_20210417_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibillity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_name', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibillity_author', to=settings.AUTH_USER_MODEL)),
                ('visible_user', models.ManyToManyField(related_name='visibillity_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
