# Generated by Django 3.2 on 2021-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_calendar', '0023_visibillity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
